### ISSUE TITLE
[type] Converting plain object to class and back adds optional fields with null value

### ISSUE THREAD

**Issue by pm0** [deepkit/deepkit-framework#127] opened 2021-08-19 03:27 UTC
Having issue with classToPlain calls adding in extra fields that were not provided in initial plain object.

Example:

    class TestClass {
      @t
      fieldA: string;

      @t
      fieldB: string;

      @t
      fieldC?: string;

      @t
      fieldD?: string;
    }

    const testData = {
      fieldA: 'a',
      fieldB: 'b'
    }

    const ptc = plainToClass(TestClass, testData);
    const ptctp = classToPlain(TestClass, ptc);

    console.log('ptc ' + JSON.stringify(ptc));
    console.log('ptctp ' + JSON.stringify(ptctp));

Output:

    ptc {"fieldA":"a","fieldB":"b"}
    ptctp {"fieldA":"a","fieldB":"b","fieldC":null,"fieldD":null}

Expecting the plain object to not have `fieldC` and `fieldD` fields.

**Comment by marcj** [comment] 2021-08-19 11:46
A unit test shows that it works as expected

```
import { expect, test } from '@jest/globals';
import 'reflect-metadata';
import { classToPlain, plainToClass, t } from '@deepkit/type';

test('127', () => {
    class TestClass {
        @t.required fieldA!: string;
        @t.required fieldB!: string;
        @t fieldC?: string;
        @t fieldD?: string;
    }

    const testData = {
        fieldA: 'a',
        fieldB: 'b'
    }

    const object = plainToClass(TestClass, testData);
    expect(object.fieldC).toBe(undefined);
    expect(object.fieldC).toBe(undefined);

    const plain = classToPlain(TestClass, object);
    expect(plain.fieldC).toBe(undefined);
    expect(plain.fieldD).toBe(undefined);

    expect(JSON.stringify(plain)).toBe(`{"fieldA":"a","fieldB":"b"}`);
});
```

So it might be that your config or compiler settings are not right. an you share your tsconfig.json? And maybe build the dist version to see what is actually in the js files.

**Comment by pm0** [comment] 2021-08-19 14:26
tsconfig.json:

    {
      "compilerOptions": {
        "allowJs": true,
        "allowSyntheticDefaultImports": true,
        "esModuleInterop": true,
        "isolatedModules": true,
        "jsx": "react",
        "lib": ["es6", "es2017", "es2019"],
        "moduleResolution": "node",
        "noEmit": true,
        "strict": true,
        "skipLibCheck": true,
        "target": "esnext",
        "baseUrl": "./src",
        "experimentalDecorators": true,
        "emitDecoratorMetadata": true,
        "strictPropertyInitialization": false
      },
      "exclude": [
        "node_modules",
        "babel.config.js",
        "metro.config.js",
        "jest.config.js"
      ]
    }

This is the built JS for the class file:

    "use strict";
    var __decorate = (this && this.__decorate) || function (decorators, target, key, desc) {
        var c = arguments.length, r = c < 3 ? target : desc === null ? desc = Object.getOwnPropertyDescriptor(target, key) : desc, d;
        if (typeof Reflect === "object" && typeof Reflect.decorate === "function") r = Reflect.decorate(decorators, target, key, desc);
        else for (var i = decorators.length - 1; i >= 0; i--) if (d = decorators[i]) r = (c < 3 ? d(r) : c > 3 ? d(target, key, r) : d(target, key)) || r;
        return c > 3 && r && Object.defineProperty(target, key, r), r;
    };
    exports.__esModule = true;
    var type_1 = require("@deepkit/type");
    var TestClass = /** @class */ (function () {
        function TestClass() {
        }
        __decorate([
            type_1.t
        ], TestClass.prototype, "fieldA");
        __decorate([
            type_1.t
        ], TestClass.prototype, "fieldB");
        __decorate([
            type_1.t
        ], TestClass.prototype, "fieldC");
        __decorate([
            type_1.t
        ], TestClass.prototype, "fieldD");
        return TestClass;
    }());

I've noticed as well for defining a `JSONEntity` manually that the same issue occurs. Example:

    const testClassPlain : JSONEntity<TestClass> = {
      fieldA: 'test',
      fieldB: 'test'
    }

Error:
`Type '{ fieldA: string; fieldB: string; }' is missing the following properties from type 'JSONEntity<TestClass>': fieldC, fieldD ts(2739)`

**Comment by marcj** [comment] 2021-08-19 14:36
The meta-data is not generated in your JS files. The correct output is:

```typescript
class TestClass {
    }
    __decorate([
        index_1.t.required,
        __metadata("design:type", String)
    ], TestClass.prototype, "fieldA", void 0);
    __decorate([
        index_1.t.required,
        __metadata("design:type", String)
    ], TestClass.prototype, "fieldB", void 0);
    __decorate([
        index_1.t,
        __metadata("design:type", String)
    ], TestClass.prototype, "fieldC", void 0);
    __decorate([
        index_1.t,
        __metadata("design:type", String)
    ], TestClass.prototype, "fieldD", void 0);
```

All those `__metadata("design:type", String)` are missing in your JS files.

**Comment by pm0** [comment] 2021-08-20 09:14
My mistake, I was looking in the wrong place for the transpiled code. For some context this is a react-native project using babel with the `@babel/plugin-proposal-decorators` and `babel-plugin-transform-typescript-metadata` plugins to handle decorators & reflection. The transpiled TestClass looks like this and is adding in the `null` fields:

```javascript
var TestClass = (_dec = Reflect.metadata("design:type", String), _dec2 = Reflect.metadata("design:type", String), _dec3 = Reflect.metadata("design:type", String), _dec4 = Reflect.metadata("design:type", String), (_class = function TestClass() {
  (0, _classCallCheck2.default)(this, TestClass);
  (0, _initializerDefineProperty2.default)(this, "fieldA", _descriptor, this);
  (0, _initializerDefineProperty2.default)(this, "fieldB", _descriptor2, this);
  (0, _initializerDefineProperty2.default)(this, "fieldC", _descriptor3, this);
  (0, _initializerDefineProperty2.default)(this, "fieldD", _descriptor4, this);
}, (_descriptor = (0, _applyDecoratedDescriptor2.default)(_class.prototype, "fieldA", [_$$_REQUIRE(_dependencyMap[10], "@deepkit/type").t, _dec], {
  configurable: true,
  enumerable: true,
  writable: true,
  initializer: null
}), _descriptor2 = (0, _applyDecoratedDescriptor2.default)(_class.prototype, "fieldB", [_$$_REQUIRE(_dependencyMap[10], "@deepkit/type").t, _dec2], {
  configurable: true,
  enumerable: true,
  writable: true,
  initializer: null
}), _descriptor3 = (0, _applyDecoratedDescriptor2.default)(_class.prototype, "fieldC", [_$$_REQUIRE(_dependencyMap[10], "@deepkit/type").t, _dec3], {
  configurable: true,
  enumerable: true,
  writable: true,
  initializer: null
}), _descriptor4 = (0, _applyDecoratedDescriptor2.default)(_class.prototype, "fieldD", [_$$_REQUIRE(_dependencyMap[10], "@deepkit/type").t, _dec4], {
  configurable: true,
  enumerable: true,
  writable: true,
  initializer: null
})), _class));
```

However for tests I managed to get it working using `ts-jest` transformer, it does not add in the `null` values. Can't get transpiled output but for `tsc` it looks like your correct output above.

**Comment by marcj** [comment] 2021-08-24 13:34
I have no knowledge about those babel plugins. Please post a reproduction repository, so I can test if it works on my machine and not to find out where the error is. Without being able to reproduce your issue I can't help you, unfortunately.

**Comment by marcj** [comment] 2022-03-13 18:48
Closing since outdated

**Closed by marcj** 2022-03-13 18:48 UTC
