### ISSUE TITLE
[typeCompiler] Array<{...}> does not work under jest / ts-jest

### ISSUE THREAD

**Issue by CristianPi** [deepkit/deepkit-framework#376] opened 2022-09-10 22:40 UTC
```typescript
enum UserRole {
  ADMIN,
  STAFF
}

export class UserA {
  name: string
  surname: string
  avatar: string
  status: string
  email: string
  password: string
  settings: any
  workers: Array<{ role: UserRole; email: string; }>; // kind 0 never, do not work
  worker1: { role: UserRole; email: string; }; // works
  workers2: { role: UserRole; email: string; }[]; // works

  static from(user: UserA) {
    return Object.assign(new UserA(), user);
  }
}
```

this works
```typescript
{ role: UserRole; email: string; }[] 
```

this not
```typescript
Array<{ role: UserRole; email: string; }>
```

**Comment by marcj** [comment] 2022-10-13 03:07
This code works in our jest/ts-jest setup fine

```typescript

    enum UserRole {
        ADMIN,
        STAFF
    }

    class UserA {
        name!: string
        surname!: string
        avatar!: string
        status!: string
        email!: string
        password!: string
        settings!: any
        workers!: Array<{ role: UserRole; email: string; }>; // kind 0 never, do not work
        worker1!: { role: UserRole; email: string; }; // works
        workers2!: { role: UserRole; email: string; }[]; // works

        static from(user: UserA) {
            return Object.assign(new UserA(), user);
        }
    }


    console.log(stringifyResolvedType(typeOf<UserA>()));
```

outputs

```
  console.log
    UserA {
      name: string;
      surname: string;
      avatar: string;
      status: string;
      email: string;
      password: string;
      settings: any;
      workers: Array<{
          role: UserRole {ADMIN: 0, STAFF: 1};
          email: string;
        }>;
      worker1: {
        role: UserRole {ADMIN: 0, STAFF: 1};
        email: string;
      };
      workers2: Array<{
          role: UserRole {ADMIN: 0, STAFF: 1};
          email: string;
        }>;
      static from(user: UserA {
          * Recursion *;
          * Recursion *;
          * Recursion *;
          * Recursion *;
          * Recursion *;
          * Recursion *;
          * Recursion *;
          * Recursion *;
          * Recursion *;
          * Recursion *;
          * Recursion *;
        }): any;
    }
```

**Comment by marcj** [comment] 2022-12-02 07:32
Closing since not reproducible and no feedback

**Closed by marcj** 2022-12-02 07:32 UTC
